# Generated by Django 5.2.5 on 2025-08-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizsubmission',
            name='attempted_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='total_time_taken',
            field=models.PositiveIntegerField(help_text='Time in seconds'),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='unattempted_count',
            field=models.PositiveIntegerField(),
        ),
    ]
