# Generated by Django 5.2.5 on 2025-08-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_quizsubmission_attempted_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizsubmission',
            old_name='unattempted_count',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='quizsubmission',
            name='answers',
        ),
    ]
